server:
  port: 8080

spring:
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        - id: movement-service
          uri: lb://movement-service
          predicates:
            - Path=/movement-service/**
          filters:
            - StripPrefix=1

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report-service/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        - id: yanki-service
          uri: lb://yanki-service
          predicates:
            - Path=/yanki-service/**
          filters:
            - StripPrefix=1

        - id: bootcoin-service
          uri: lb://bootcoin-service
          predicates:
            - Path=/bootcoin-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true