server:
  port: 8080  # Puerto del gateway

spring:
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://localhost:8888  # Conexión al Config Server

  # Configuración de las rutas del gateway
  cloud:
    gateway:
      routes:
        - id: client-service  # Ruta para client-service
          uri: http://localhost:8081
          predicates:
            - Path=/client-service/**  # Escucha peticiones que empiecen con /client-service/
          filters:
            - StripPrefix=1  # Elimina /client-service del path antes de redirigir

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        - id: movement-service
          uri: http://localhost:8083
          predicates:
            - Path=/movement-service/**
          filters:
            - StripPrefix=1

        - id: report-service
          uri: http://localhost:8084
          predicates:
            - Path=/report-service/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1